---
title: "Gather Physician Data Starting With NPI Numbers"
author: 
  - Tyler Muffly, MD
output: 
  rmarkdown::html_vignette:
    df_print: kable
description: >
  A function to search names from National Provider Identifier (NPI) numbers.
vignette: >
  %\VignetteIndexEntry{Gather Physician Data Starting With NPI Numbers}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---
# Overview
The `validate_and_remove_invalid_npi` function is designed to help you process datasets containing National Provider Identifier (NPI) numbers with `search_by_taxonomy`. It validates the format of NPIs using the npi package and removes rows with missing or invalid NPIs. This vignette will guide you through its usage.

## Step 1
### Installation
Before you can harness the power of the `search_by_taxonomy` function, it is essential to ensure that you have the `tyler` package installed. You can effortlessly install it using the following command:

```{r setup, include = FALSE}
# install.packages("dplyr")
# install.packages("npi")
# install.packages("readr")
library(tyler)
```
```r
library(tyler)
```

# Example Usage
## Understanding National Provider Identifier
A valid National Provider Identifier (NPI) number in the United States should meet certain criteria to be considered legitimate. Here are the key characteristics that make an NPI number valid:

* 1. Length: An NPI number consists of ten digits. It should not be shorter or longer than ten digits.

* 2. Numeric Digits: All characters in an NPI must be numeric digits (0-9). No letters, symbols, or special characters are allowed.

* 3. Luhn Algorithm: While the Luhn algorithm is commonly used to validate credit card numbers, it is applied to NPI numbers. NPIs are supposedly checksummed using the Luhn algorithm.

In summary, a valid NPI number should have ten numeric digits and no additional characters. 

To validate NPI numbers programmatically, you can check their length and confirm that they contain only numeric digits (0-9). However, it's important to note that the specific format and validation rules for NPI numbers are defined by the National Plan and Provider Enumeration System (NPPES).

## Step 2: Prepare Your Data
You can provide your data as either a dataframe or a CSV file in the argument `input_data`.

* If your data is a dataframe, simply pass it as the input_data parameter.
* If your data is in a CSV file, pass the file path as the input_data parameter.

```r
# Example using a dataframe
data_df <- data.frame(npi = c("1234567890", "9876543210", "invalid_npi"))
valid_df <- validate_and_remove_invalid_npi(input_data)

# Example using a CSV file
input_data <- "path/to/your/file.csv"
valid_df <- validate_and_remove_invalid_npi(input_data)
```

## Step 3: Data Validation
The function will validate the NPIs in your data. It performs the following checks:

* Removes rows with missing NPIs.
* Removes rows with empty NPIs.
* Ensures that the NPIs have a valid format (numeric and 10 characters in length).
* Invalid NPIs will be removed, and a new column named "npi_is_valid" will be added to indicate NPI validity.

```r
# A tibble: 7,494 × 7
   sub1  first_name last_name          npi state         city             npi_is_valid
   <chr> <chr>      <chr>            <dbl> <chr>         <chr>            <lgl>       
 1 MFM   Ryan       Schlueter   1053601807 Georgia       Atlanta          TRUE        
 2 FPM   Laura      Martin      1528351640 Florida       Miramar          TRUE        
 3 REI   Lauren     Bishop      1063703494 New York      New York         TRUE        
 4 MFM   Jamie      Szczepanski 1376862383 New York      Buffalo          TRUE  
```

## Step 4: Get the Valid Data
The function will return a dataframe containing only the valid NPI numbers.


## Step 5:  Validating NPI numbers is needed before searching by NPI number in the CMS databases.
An error can break your results and error handling is beyond my knowledge base now.  

In this use case we use `validate_and_remove_invalid_npi` function before searching physician demographics (medical school, etc) in the National Downloadable File from CMS (https://data.cms.gov/provider-data/dataset/mj5m-pzi6).  The database is update monthly so we know that this data is fresh and then `validate_and_remove_invalid_npi` makes it clean.  Fresh and clean!

```r
df_updated <- NULL

retrieve_clinician_data <- function(input_data) {
  library(provider)
  library(dplyr)
  library(purrr)
  library(readr)
  library(tidyr)
  library(lubridate)
  library(memoise)
  library(zipcodeR)

  # Load libraries
  #remotes::install_github("andrewallenbruce/provider")

  if (is.data.frame(input_data)) {
    # Input is a dataframe
    df <- input_data
  } else if (is.character(input_data)) {
    # Input is a file path to a CSV
    df <- readr::read_csv(input_data)
  } else {
    stop("Input must be a dataframe or a file path to a CSV.")
  }

  # Clean the NPI numbers
  df <- validate_and_remove_invalid_npi(df)
```
After this step we can confidently feed in all the NPI numbers to the `provider::clinicians` function without fear of NPI number error.  

```r
  # Function to retrieve clinician data for a single NPI
  get_clinician_data <- function(npi) {
    if (!is.numeric(npi) || nchar(npi) != 10) {
      cat("Invalid NPI:", npi, "\n")
      return(NULL)  # Skip this NPI
    }

    clinician_info <- provider::clinicians(npi = npi)
    if (is.null(clinician_info)) {
      cat("No results for NPI:", npi, "\n")
    } else {
      return(clinician_info)
    }
    Sys.sleep(1)
  }

  #df <- df %>% head(5) #test

  # Loop through the "npi" column and get clinician data
  df_updated <- df %>%
    dplyr::mutate(row_number = row_number()) %>%
    dplyr::mutate(clinician_data = purrr::map(npi, get_clinician_data)) %>%
    tidyr::unnest(clinician_data, names_sep = "_") %>%
    dplyr::distinct(npi, .keep_all = TRUE)

  return(df_updated)
}
```

Specifically this was our use case.  We see the CSV get read in then the `provider::clinicians` searched.  The output is only the people who had no results but it skips the people who did have results.  
```r
# Call the retrieve_clinician_data function with an NPI value
input_data <- ("~/Dropbox (Personal)/workforce/subspecialists_only.csv")
clinician_data <- retrieve_clinician_data(input_data)

Rows: 7498 Columns: 9                                                                                                                                        
── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr (8): sub1, first_name, last_name, state, name.x, city, GenderPhysicianCompare, Zip CodePhysicianCompare
dbl (1): npi

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
✖ No results for npi = 1063703494
No results for NPI: 1063703494 
✖ No results for npi = 1104052125
No results for NPI: 1104052125 
✖ No results for npi = 1972745586
No results for NPI: 1972745586 
✖ No results for npi = 1427386804
No results for NPI: 1427386804 
✖ No results for npi = 1942586581
No results for NPI: 1942586581 
```

# Conclusion
The validate_and_remove_invalid_npi function is a handy tool for cleaning and validating datasets with NPI numbers. By following the steps outlined in this vignette, you can ensure that your data contains only valid NPIs for further analysis and processing.

# Features and bugs
If you have ideas for other features that would make name handling easier, or find a bug, the best approach is to either report it or add it!
