#' Plot and Save Estimated Marginal Means (EMMs)
#'
#' This function computes the estimated marginal means (EMMs) from a model object, creates a plot of the EMMs with confidence intervals, and saves the plot to a specified directory. This is particularly useful in studies like mystery caller studies where you need to analyze differences in outcomes such as appointment wait times across different groups or treatments.
#'
#' @param model_object A fitted model object from which EMMs are to be computed. This can be a generalized linear model (GLM), linear model, or other suitable models.
#' @param specs A character string specifying the predictor variable(s) for which EMMs are to be computed. For example, this could be the treatment groups, scenarios, or demographic variables.
#' @param variable_of_interest A character string specifying the variable to be plotted on the x-axis. Typically, this would be the same as the `specs`.
#' @param color_by A character string specifying the variable used to color the points and error bars. This could be a categorical variable like gender, insurance type, or academic affiliation.
#' @param output_dir A character string specifying the directory where the plot will be saved. Defaults to "Ari/Figures".
#'
#' @return Invisibly returns a list containing the estimated marginal means data (`data`) and the ggplot object (`plot`).
#'
#' @details The function computes EMMs using the `emmeans` package, which provides adjusted means (or other summary statistics) for the levels of factors, corrected for the influence of other predictors in the model. This is particularly useful in the context of mystery caller studies, where you might want to compare outcomes such as appointment wait times between different insurance types, scenarios, or demographic groups, while controlling for potential confounders.
#'
#' The plot generated by this function displays the EMMs along with their 95% confidence intervals, making it easy to visualize the differences between groups. The plot is saved to a specified directory with a unique filename that includes a timestamp.
#'
#' @import emmeans ggplot2 dplyr
#' @importFrom rlang .data
#'
#' @examples
#' \dontrun{
#' # Example 1: Comparing Appointment Wait Times Between Scenarios
#' # Assume 'model' is a fitted GLM object with appointment wait time as the outcome
#' result <- plot_and_save_emmeans(
#'   model_object = model,
#'   specs = "scenario",
#'   variable_of_interest = "scenario",
#'   color_by = "insurance",
#'   output_dir = "Figures/ScenarioComparison"
#' )
#'
#' # Example 2: Comparing EMMs Across Different Insurance Types
#' # Assume 'model' is a fitted GLM object
#' result <- plot_and_save_emmeans(
#'   model_object = model,
#'   specs = "insurance",
#'   variable_of_interest = "insurance",
#'   color_by = "academic",
#'   output_dir = "Figures/InsuranceComparison"
#' )
#'
#' # Example 3: Visualizing EMMs for Different Age Groups in a Mystery Caller Study
#' # Assume 'model' is a fitted GLM object with age groups as a factor
#' result <- plot_and_save_emmeans(
#'   model_object = model,
#'   specs = "age_group",
#'   variable_of_interest = "age_group",
#'   color_by = "gender",
#'   output_dir = "Figures/AgeGroupComparison"
#' )
#'
#' # Example 4: Interaction Effects Between Gender and Insurance Type
#' # Assume 'model' is a fitted GLM object
#' result <- plot_and_save_emmeans(
#'   model_object = model,
#'   specs = c("gender", "insurance"),
#'   variable_of_interest = "gender",
#'   color_by = "insurance",
#'   output_dir = "Figures/InteractionEffects"
#' )
#' }
#'
#' @export
plot_and_save_emmeans <- function(model_object, specs, variable_of_interest, color_by, output_dir = "Ari/Figures") {
  # Load necessary packages
  if (!requireNamespace("emmeans", quietly = TRUE)) {
    stop("Package 'emmeans' is required but not installed.")
  }
  if (!requireNamespace("ggplot2", quietly = TRUE)) {
    stop("Package 'ggplot2' is required but not installed.")
  }
  if (!requireNamespace("dplyr", quietly = TRUE)) {
    stop("Package 'dplyr' is required but not installed.")
  }

  # Input validation
  if (is.null(model_object)) {
    stop("'model_object' cannot be NULL.")
  }
  if (!is.character(specs) || length(specs) == 0) {
    stop("'specs' must be a non-empty character vector.")
  }
  if (!is.character(variable_of_interest) || length(variable_of_interest) != 1) {
    stop("'variable_of_interest' must be a single character string.")
  }
  if (!is.character(color_by) || length(color_by) != 1) {
    stop("'color_by' must be a single character string.")
  }
  if (!is.character(output_dir) || length(output_dir) != 1) {
    stop("'output_dir' must be a single character string.")
  }

  # Get the current timestamp for unique file naming
  timestamp <- format(Sys.time(), "%Y%m%d_%H%M%S")

  # Compute estimated marginal means
  cat("Computing estimated marginal means...\n")
  edata <- tryCatch({
    emmeans::emmeans(object = model_object, specs = specs, type = "response") %>%
      as.data.frame()
  }, error = function(e) {
    stop("Error computing estimated marginal means: ", e$message)
  })

  # Log the retrieved data
  cat("Estimated data:\n")
  print(edata)

  # Validate that required columns exist in the emmeans output
  required_cols <- c("rate", "asymp.LCL", "asymp.UCL", variable_of_interest, color_by)
  missing_cols <- setdiff(required_cols, names(edata))
  if (length(missing_cols) > 0) {
    stop("Required columns missing from emmeans output: ", paste(missing_cols, collapse = ", "))
  }

  # Check the range of the estimated data
  rate_range <- range(c(edata$asymp.LCL, edata$asymp.UCL), na.rm = TRUE)
  cat("Range of estimated marginal means with CIs:", rate_range, "\n")

  # Create the plot
  cat("Creating the plot...\n")
  p <- ggplot2::ggplot(edata, ggplot2::aes(x = .data[[variable_of_interest]], y = .data[["rate"]])) +
    ggplot2::geom_point(ggplot2::aes(color = .data[[color_by]]), size = 2, stroke = 2,
                        position = ggplot2::position_dodge(width = 0.2)) +
    ggplot2::geom_errorbar(ggplot2::aes(ymin = .data[["asymp.LCL"]], ymax = .data[["asymp.UCL"]], color = .data[[color_by]]),
                           width = 0.2, position = ggplot2::position_dodge(width = 0.2)) +
    ggplot2::ylim(rate_range[1] - 5, rate_range[2] + 5) +
    ggplot2::ggtitle(paste("Estimated Marginal Means -", variable_of_interest)) +
    ggplot2::ylab("Estimated Marginal Means for Waiting Time in Days\nMean ± 95% CI") +
    ggplot2::theme_minimal() +
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1, vjust = 1, size = 10, color = "black"),
                   legend.position = "bottom") +
    ggplot2::scale_x_discrete(labels = function(x) gsub(" ", "\n", x))

  # Ensure the output directory exists
  if (!dir.exists(output_dir)) {
    dir.create(output_dir, recursive = TRUE)
  }

  # Save the plot with specific dimensions
  file_name <- paste0(output_dir, "/interaction_", variable_of_interest, "_comparison_plot_", timestamp, ".png")
  cat("Saving plot to:", file_name, "\n")
  ggplot2::ggsave(filename = file_name, plot = p, width = 10, height = 6, bg = "white")

  cat("Plot saved successfully.\n")

  # Return the data and plot invisibly
  invisible(list(data = edata, plot = p))
}
