#' @importFrom methods is
#' @importFrom stats coef density fitted model.frame model.response poisson predict runif sd
#' @importFrom utils capture.output packageVersion str tail write.csv
NULL

utils::globalVariables(c(
  ".",
  ".isochrone_memo",
  "ACOG_District",
  "GEOID",
  "NAME",
  "State",
  "State_Abbreviations",
  "Subregion",
  "academic",
  "address",
  "addresses_country_name",
  "age_label",
  "area_method",
  "basic_credential",
  "basic_first_name",
  "basic_last_name",
  "basic_middle_name",
  "bg_area",
  "block group",
  "credential",
  "credential_clean",
  "credential_lower",
  "doctor_id",
  "dr_name",
  "drive_time",
  "female_population",
  "first_name",
  "for_redcap",
  "geometry",
  "grid_id",
  "hrrcity",
  "id",
  "id_number",
  "insurance",
  "int_var",
  "intersect_area",
  "lat",
  "long",
  "male_population",
  "mean_pred",
  "name",
  "npi",
  "phone_number",
  "physician_count",
  "population",
  "postal",
  "practice_name",
  "pred",
  "random_id",
  "reproductive_age_female",
  "response_var",
  "share",
  "state",
  "state_name",
  "taxonomies_desc",
  "total_population",
  "var_interest",
  "ci_lower",
  "ci_upper",
  "fitted",
  "irr",
  "n_per_arm",
  "residuals",
  "sqrt_abs_resid",
  "term",
  "value",
  ":=",
  "group",
  "rate_pct",
  "status",
  "pct",
  "label",
  "men_18_90",
  "men_18_90_moe",
  "women_18_90",
  "women_18_90_moe",
  "adults_18_90",
  "adults_18_90_moe",
  "addr1_dir",
  "addr1_suf",
  "address1_norm",
  "tmp_units",
  "tmp_units_addr1",
  "tmp_units_addr2"
))

.onAttach <- function(libname, pkgname) {
  if (interactive() && runif(1) < 0.25) {
    packageStartupMessage(
      "If you use mysterycall in published research, please cite it:\n",
      "  citation(\"mysterycall\")"
    )
  }
}
