# Build and deploy pkgdown site to GitHub Pages
# Only runs after successful R-CMD-check
# Based on: https://github.com/r-lib/actions/tree/v2/examples

name: pkgdown

on:
  workflow_run:
    workflows: ["R-CMD-check"]
    types:
      - completed

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  pkgdown:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' }}
    runs-on: ubuntu-latest
    concurrency:
      group: pkgdown-${{ github.event.workflow_run.head_branch || github.ref }}
      cancel-in-progress: true

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Configure git safe directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev \
            libgit2-dev libgdal-dev libgeos-dev libproj-dev libudunits2-dev \
            libfftw3-dev libtiff5-dev libjpeg-dev libpng-dev qpdf

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          cache: true

      - name: Build pkgdown site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Disable Jekyll
        run: touch docs/.nojekyll

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: docs
          clean: true
